### ISSUE TITLE
Json报错，MacOS 12.5 Macbook Air 2022 M2

### ISSUE THREAD

**Issue by AXAShield** [Koileo/ticket_for_allcpp#4]
在正常选择”捡漏“后，出现以下报错：

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/g/ticket_for_allcpp/main.py", line 160, in process_thread
    parsed_resp = json.loads(resp)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
g@GdeMacBook-Air ticket_for_allcpp %

**Comment by AXAShield** [comment]
已解决 不影响使用
